# Generated by Django 5.1.4 on 2025-01-02 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Banner Image')),
                ('title', models.CharField(max_length=200, verbose_name='Banner Title')),
                ('subtitle', models.TextField(blank=True, verbose_name='Banner Subtitle')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryLevel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Level 1')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryLevel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Level 2')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level2_categories', to='home.categorylevel1', verbose_name='Parent Category (Level 1)')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryLevel3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Level 3')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level3_categories', to='home.categorylevel2', verbose_name='Parent Category (Level 2)')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Product Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Product Price')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Product Image')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock Quantity')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='home.categorylevel3', verbose_name='Category')),
            ],
        ),
    ]
