# Generated by Django 5.1.4 on 2025-01-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_aboutusbanner_chairmanmessage_companyvoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel/', verbose_name='Carousel Image')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Alt Text')),
            ],
        ),
    ]
