# Generated by Django 5.1.4 on 2025-01-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_carouselimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Branch Name')),
                ('image', models.ImageField(upload_to='branches/', verbose_name='Branch Image')),
                ('description', models.TextField(blank=True, verbose_name='Branch Description')),
            ],
        ),
    ]
