# Generated by Django 5.1.4 on 2025-01-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosection',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='about_us/backgrounds/', verbose_name='Background Image'),
        ),
    ]
