# Generated by Django 5.1.4 on 2025-01-03 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_videosection_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosection',
            name='video_link',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.RegexValidator(code='invalid_youtube_url', message='Not a valid YouTube URL. Please provide a valid embed link.', regex='^(https?://)?(www\\.)?(youtube\\.com|youtu\\.?be)/.+$')], verbose_name='Video Link'),
        ),
    ]
