# Generated by Django 5.1.4 on 2025-01-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_videosection_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosection',
            name='video_link',
            field=models.URLField(blank=True, null=True, verbose_name='Video Link'),
        ),
    ]
