# Generated by Django 5.1.4 on 2025-01-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_missionvision_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_order_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
