# Generated by Django 5.1.4 on 2025-01-03 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_footer_links_footer_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='links',
        ),
    ]
