# Generated by Django 5.1.4 on 2025-01-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_footer_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='logo',
            field=models.ImageField(default=123, upload_to='logo/', verbose_name='Site logo'),
            preserve_default=False,
        ),
    ]
