# Generated by Django 5.1.4 on 2025-01-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_appointment_alter_contactus_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
