# Generated by Django 5.1.4 on 2025-01-05 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_appointment_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='title',
        ),
    ]
