# Generated by Django 5.1.4 on 2025-01-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_remove_appointment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
