# Generated by Django 5.1.4 on 2025-01-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_appointment_viewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='viewed',
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_read',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
