# Generated by Django 5.1.4 on 2025-01-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_remove_appointment_viewed_appointment_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
