# Generated by Django 5.1.4 on 2025-01-05 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_appointment_viewed_alter_appointment_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='is_read',
        ),
    ]
