# Generated by Django 5.1.4 on 2025-01-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_companyinquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone_number',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Phone Number'),
        ),
    ]
