# Generated by Django 5.1.4 on 2025-01-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_contactus_address_contactus_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
    ]
