# Generated by Django 5.1.4 on 2025-01-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_contactus_latitude_contactus_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='plus_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Plus Code'),
        ),
    ]
