# Generated by Django 5.1.4 on 2025-01-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_contactus_plus_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Google Maps API Key'),
        ),
    ]
