# Generated by Django 5.1.4 on 2025-01-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_contactus_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='plus_code',
        ),
        migrations.AddField(
            model_name='contactus',
            name='embed_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Embed Code'),
        ),
    ]
