# Generated by Django 5.1.4 on 2025-01-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_remove_contactus_latitude_remove_contactus_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='embed_code',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Embed Code'),
        ),
    ]
