# Generated by Django 5.1.4 on 2025-01-19 06:22

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_alter_contactus_embed_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Product Color'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('US: 0 = EU: 15', 'US: 0 = EU: 15'), ('US: 1 = EU: 16', 'US: 1 = EU: 16'), ('US: 2 = EU: 17', 'US: 2 = EU: 17'), ('US: 3 = EU: 18', 'US: 3 = EU: 18'), ('US: 4 = EU: 19', 'US: 4 = EU: 19'), ('US: 5 = EU: 20', 'US: 5 = EU: 20'), ('US: 6 = EU: 22', 'US: 6 = EU: 22'), ('US: 7 = EU: 23', 'US: 7 = EU: 23'), ('US: 8 = EU: 24', 'US: 8 = EU: 24'), ('US: 9 = EU: 25', 'US: 9 = EU: 25'), ('US: 10 = EU: 27', 'US: 10 = EU: 27'), ('US: 11 = EU: 28', 'US: 11 = EU: 28'), ('US: 12 = EU: 30', 'US: 12 = EU: 30'), ('US: 13 = EU: 32', 'US: 13 = EU: 32'), ('US: 1 = EU: 33', 'US: 1 = EU: 33'), ('US: 1.5 = EU: 33.5', 'US: 1.5 = EU: 33.5'), ('US: 2 = EU: 34', 'US: 2 = EU: 34'), ('US: 2.5 = EU: 34.5', 'US: 2.5 = EU: 34.5'), ('US: 3 = EU: 35', 'US: 3 = EU: 35'), ('US: 3.5 = EU: 35.5', 'US: 3.5 = EU: 35.5'), ('US: 4 = EU: 36', 'US: 4 = EU: 36'), ('US: 4.5 = EU: 36.5', 'US: 4.5 = EU: 36.5'), ('US: 5 = EU: 37', 'US: 5 = EU: 37'), ('US: 5.5 = EU: 38', 'US: 5.5 = EU: 38'), ('US: 6 = EU: 39', 'US: 6 = EU: 39'), ('US: 6.5 = EU: 39.5', 'US: 6.5 = EU: 39.5'), ('US: 7 = EU: 40', 'US: 7 = EU: 40'), ('US: 7.5 = EU: 40.5', 'US: 7.5 = EU: 40.5'), ('US: 8 = EU: 41', 'US: 8 = EU: 41'), ('US: 8.5 = EU: 42', 'US: 8.5 = EU: 42'), ('US: 9 = EU: 43', 'US: 9 = EU: 43'), ('US: 9.5 = EU: 43.5', 'US: 9.5 = EU: 43.5'), ('US: 10 = EU: 44', 'US: 10 = EU: 44'), ('US: 10.5 = EU: 44.5', 'US: 10.5 = EU: 44.5'), ('US: 11 = EU: 45', 'US: 11 = EU: 45'), ('US: 11.5 = EU: 45.5', 'US: 11.5 = EU: 45.5'), ('US: 12 = EU: 46', 'US: 12 = EU: 46'), ('US: 12.5 = EU: 46.5', 'US: 12.5 = EU: 46.5'), ('US: 13 = EU: 47', 'US: 13 = EU: 47')], max_length=20, null=True, verbose_name='Product Size'),
        ),
    ]
