# Generated by Django 5.1.4 on 2025-01-19 07:30

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_product_color_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='color_1',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Product Color 1'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_2',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Product Color 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_3',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Product Color 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_4',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Product Color 4'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_5',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Product Color 5'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Product Size 1'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Product Size 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Product Size 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_4',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Product Size 4'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_5',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Product Size 5'),
        ),
    ]
