# Generated by Django 5.1.4 on 2025-01-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_alter_product_color_1_alter_product_color_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='minimum_order_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
