# Generated by Django 5.1.4 on 2025-01-19 07:35

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_alter_product_minimum_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color_1',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='Enter color hex code (e.g., #FFFFFF)', image_field=None, max_length=25, null=True, samples=None, verbose_name='Product Color 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_2',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='Enter color hex code (e.g., #FFFFFF)', image_field=None, max_length=25, null=True, samples=None, verbose_name='Product Color 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_3',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='Enter color hex code (e.g., #FFFFFF)', image_field=None, max_length=25, null=True, samples=None, verbose_name='Product Color 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_4',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='Enter color hex code (e.g., #FFFFFF)', image_field=None, max_length=25, null=True, samples=None, verbose_name='Product Color 4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_5',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='Enter color hex code (e.g., #FFFFFF)', image_field=None, max_length=25, null=True, samples=None, verbose_name='Product Color 5'),
        ),
    ]
