# Generated by Django 5.1.4 on 2025-01-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_alter_product_color_1_alter_product_color_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recommend',
            field=models.BooleanField(default=False, verbose_name='Want to recommend? '),
        ),
    ]
