# Generated by Django 5.1.4 on 2025-01-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_product_image_1_product_image_2_product_image_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=2, upload_to='products/', verbose_name='Product Image'),
            preserve_default=False,
        ),
    ]
