# Generated by Django 5.1.4 on 2025-02-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_aboutus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosection',
            name='background_image',
            field=models.ImageField(default=12, upload_to='about_us/backgrounds/', verbose_name='Background Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videosection',
            name='video_link',
            field=models.URLField(verbose_name='Video Link'),
        ),
    ]
